/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author hp
 */
public class AboutForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginActivity
     */
    public AboutForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutPanel = new javax.swing.JPanel();
        aboutTitleLabel = new javax.swing.JLabel();
        developer1Label = new javax.swing.JLabel();
        guide1Label = new javax.swing.JLabel();
        okayButton = new javax.swing.JButton();
        developerSectionLabel = new javax.swing.JLabel();
        guideSectionLabel = new javax.swing.JLabel();
        developer2Label = new javax.swing.JLabel();
        guide2Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SKNCOECDIS v18.1 - Departmental Library");
        setBackground(new java.awt.Color(235, 232, 247));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setResizable(false);

        aboutPanel.setBackground(new java.awt.Color(235, 232, 247));
        aboutPanel.setPreferredSize(new java.awt.Dimension(640, 453));

        aboutTitleLabel.setFont(new java.awt.Font("Century Schoolbook", 3, 28)); // NOI18N
        aboutTitleLabel.setForeground(new java.awt.Color(131, 56, 209));
        aboutTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64px/About.png"))); // NOI18N
        aboutTitleLabel.setText("SKNCOECDIS v.18.1");

        developer1Label.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        developer1Label.setForeground(new java.awt.Color(131, 106, 209));
        developer1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developer1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/Developer.png"))); // NOI18N
        developer1Label.setText("Satyam Sanjay Jadhav, TE, 2018-2019");

        guide1Label.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        guide1Label.setForeground(new java.awt.Color(131, 106, 209));
        guide1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guide1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/Guidance.png"))); // NOI18N
        guide1Label.setText("Professor. Sandip A. Kahate");

        okayButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        okayButton.setForeground(new java.awt.Color(131, 56, 209));
        okayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/Okay.png"))); // NOI18N
        okayButton.setText("Okay");
        okayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okayButtonActionPerformed(evt);
            }
        });

        developerSectionLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        developerSectionLabel.setForeground(new java.awt.Color(131, 56, 209));
        developerSectionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developerSectionLabel.setText("designed developed by ");

        guideSectionLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        guideSectionLabel.setForeground(new java.awt.Color(131, 56, 209));
        guideSectionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guideSectionLabel.setText("guided by ");

        developer2Label.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        developer2Label.setForeground(new java.awt.Color(131, 106, 209));
        developer2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developer2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/Developer.png"))); // NOI18N
        developer2Label.setText("Omkar Mahadeo Kumbhar, TE, 2018-2019");

        guide2Label.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        guide2Label.setForeground(new java.awt.Color(131, 106, 209));
        guide2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guide2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/Guidance.png"))); // NOI18N
        guide2Label.setText("Dr. Parikshit N. Mahalle");

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(okayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelLayout.createSequentialGroup()
                        .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(guide2Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guide1Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aboutTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(developer1Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(developerSectionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guideSectionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(developer2Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(developerSectionLabel)
                .addGap(18, 18, 18)
                .addComponent(developer1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(developer2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guideSectionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guide1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guide2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(okayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okayButtonActionPerformed
        GUI.libraryInchargeInterfaceFrame.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_okayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginForm().setVisible(true);
//                
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel aboutTitleLabel;
    private javax.swing.JLabel developer1Label;
    private javax.swing.JLabel developer2Label;
    private javax.swing.JLabel developerSectionLabel;
    private javax.swing.JLabel guide1Label;
    private javax.swing.JLabel guide2Label;
    private javax.swing.JLabel guideSectionLabel;
    private javax.swing.JButton okayButton;
    // End of variables declaration//GEN-END:variables
}
