/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DatabaseAccessObjects.QueryObjects.AddSubjectAttributes;
import DatabaseAccessObjects.ResultObjects.DomainQueryResult;
import DatabaseAccessObjects.ResultObjects.SubjectQueryResult;
import LibraryIncharge.ServerRequests;
import java.awt.Color;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class AddSubjectForm extends javax.swing.JFrame {

    /**
     * Creates new form verifyStudentForm
     */
    boolean correctInput = true;
    Color forgroundColor = new Color(131, 56, 209);
    Color backgroundColor = new Color(235, 232, 247);

    public AddSubjectForm(List<DomainQueryResult> domainQueryResultList) {
        initComponents();
        domainIDComboBox.removeAllItems();
        for (int i = 0; i < domainQueryResultList.size(); i++) {
            domainIDComboBox.addItem(domainQueryResultList.get(i).domain_id + " : " + domainQueryResultList.get(i).domain_name);
        }
        domainIDComboBox.setSelectedIndex(-1);
        domainIDComboBox.setForeground(forgroundColor);
        domainIDComboBox.setBackground(backgroundColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addSubjectPanel = new javax.swing.JPanel();
        addSubjectLable = new javax.swing.JLabel();
        semesterLabel = new javax.swing.JLabel();
        subjectNameLabel = new javax.swing.JLabel();
        abbreviationLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        domainIDLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        abbreviationText = new javax.swing.JTextField();
        subjectNameText = new javax.swing.JTextField();
        yearComboBox = new javax.swing.JComboBox<>();
        domainIDComboBox = new javax.swing.JComboBox<>();
        examPatternLabel = new javax.swing.JLabel();
        examPatternText = new javax.swing.JTextField();
        semesterComboBox = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SKNCOECDIS v.18.1 - Departmental Library");
        setResizable(false);

        addSubjectPanel.setBackground(new java.awt.Color(235, 232, 247));

        addSubjectLable.setFont(new java.awt.Font("Century Schoolbook", 3, 28)); // NOI18N
        addSubjectLable.setForeground(new java.awt.Color(131, 56, 209));
        addSubjectLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addSubjectLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64px/Edit2.png"))); // NOI18N
        addSubjectLable.setText("Add Subject");

        semesterLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        semesterLabel.setForeground(new java.awt.Color(131, 56, 209));
        semesterLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        semesterLabel.setText("semester : ");

        subjectNameLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        subjectNameLabel.setForeground(new java.awt.Color(131, 56, 209));
        subjectNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subjectNameLabel.setText("subject name : ");

        abbreviationLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        abbreviationLabel.setForeground(new java.awt.Color(131, 56, 209));
        abbreviationLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        abbreviationLabel.setText("abbreviation : ");

        yearLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(131, 56, 209));
        yearLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yearLabel.setText("year : ");

        domainIDLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        domainIDLabel.setForeground(new java.awt.Color(131, 56, 209));
        domainIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        domainIDLabel.setText("domain id : ");

        messageLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(131, 56, 209));
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText("enter details to add subject");

        cancelButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(131, 56, 209));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/CancelButton.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(131, 56, 209));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/AddButton.png"))); // NOI18N
        addButton.setText("Add");
        addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        abbreviationText.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        abbreviationText.setForeground(new java.awt.Color(131, 106, 209));
        abbreviationText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 106, 209)));
        abbreviationText.setSelectionColor(new java.awt.Color(203, 192, 235));
        abbreviationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abbreviationTextActionPerformed(evt);
            }
        });
        abbreviationText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                abbreviationTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                abbreviationTextKeyTyped(evt);
            }
        });

        subjectNameText.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        subjectNameText.setForeground(new java.awt.Color(131, 106, 209));
        subjectNameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 106, 209)));
        subjectNameText.setSelectionColor(new java.awt.Color(203, 192, 235));
        subjectNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                subjectNameTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                subjectNameTextKeyTyped(evt);
            }
        });

        yearComboBox.setBackground(new java.awt.Color(235, 232, 247));
        yearComboBox.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        yearComboBox.setForeground(new java.awt.Color(131, 106, 209));
        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FE", "SE", "TE", "BE" }));
        yearComboBox.setSelectedIndex(-1);
        yearComboBox.setToolTipText("");
        yearComboBox.setAutoscrolls(true);
        yearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboBoxActionPerformed(evt);
            }
        });

        domainIDComboBox.setBackground(new java.awt.Color(235, 232, 247));
        domainIDComboBox.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        domainIDComboBox.setForeground(new java.awt.Color(131, 106, 209));
        domainIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        domainIDComboBox.setSelectedIndex(-1);
        domainIDComboBox.setToolTipText("");
        domainIDComboBox.setAutoscrolls(true);
        domainIDComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domainIDComboBoxActionPerformed(evt);
            }
        });

        examPatternLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        examPatternLabel.setForeground(new java.awt.Color(131, 56, 209));
        examPatternLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        examPatternLabel.setText("exam pattern : ");

        examPatternText.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        examPatternText.setForeground(new java.awt.Color(131, 106, 209));
        examPatternText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 106, 209)));
        examPatternText.setSelectionColor(new java.awt.Color(203, 192, 235));
        examPatternText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                examPatternTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                examPatternTextKeyTyped(evt);
            }
        });

        semesterComboBox.setBackground(new java.awt.Color(235, 232, 247));
        semesterComboBox.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        semesterComboBox.setForeground(new java.awt.Color(131, 106, 209));
        semesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        semesterComboBox.setSelectedIndex(-1);
        semesterComboBox.setToolTipText("");
        semesterComboBox.setAutoscrolls(true);
        semesterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addSubjectPanelLayout = new javax.swing.GroupLayout(addSubjectPanel);
        addSubjectPanel.setLayout(addSubjectPanelLayout);
        addSubjectPanelLayout.setHorizontalGroup(
            addSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSubjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSubjectLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addSubjectPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addSubjectPanelLayout.createSequentialGroup()
                        .addGroup(addSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(examPatternLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addSubjectPanelLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(subjectNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(semesterLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(abbreviationLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yearLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(domainIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(domainIDComboBox, 0, 359, Short.MAX_VALUE)
                            .addComponent(yearComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(abbreviationText)
                            .addComponent(subjectNameText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(examPatternText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(semesterComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        addSubjectPanelLayout.setVerticalGroup(
            addSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSubjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addSubjectLable, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abbreviationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abbreviationText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semesterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(examPatternLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(examPatternText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(domainIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(domainIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addSubjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addSubjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        boolean enteredAllAttributes = true;
        AddSubjectAttributes addSubjectAttributes = new AddSubjectAttributes();
        try {
            if (!subjectNameText.getText().equals("")) {
                addSubjectAttributes.subject_name = subjectNameText.getText();
            } else {
                enteredAllAttributes = false;
            }

            if (!abbreviationText.getText().equals("")) {
                addSubjectAttributes.subject_abbreviation = abbreviationText.getText();
            } else {
                enteredAllAttributes = false;
            }

            if (semesterComboBox.getSelectedIndex() > -1) {
                addSubjectAttributes.semester = semesterComboBox.getSelectedItem().toString();
            } else {
                enteredAllAttributes = false;
            }

            if (yearComboBox.getSelectedIndex() > -1) {
                addSubjectAttributes.academic_year = yearComboBox.getSelectedItem().toString();
            } else {
                enteredAllAttributes = false;
            }

            if (!examPatternText.getText().equals("")) {
                addSubjectAttributes.exam_pattern = examPatternText.getText();
            }

            if (domainIDComboBox.getSelectedIndex() > -1) {
                addSubjectAttributes.domain_id = Integer.parseInt(String.valueOf(domainIDComboBox.getSelectedItem().toString().toCharArray(), 0, domainIDComboBox.getSelectedItem().toString().indexOf(':') - 1));
            } else {
                enteredAllAttributes = false;
            }

            if (enteredAllAttributes && correctInput) {
                //validate subject for duplication
                boolean weather_subject_exist = false;
                List<SubjectQueryResult> subject_list = ServerRequests.getSubjectList();
                for (SubjectQueryResult subject : subject_list) {
                    if (subject.subject_name.equalsIgnoreCase(addSubjectAttributes.subject_name) && subject.exam_pattern.equalsIgnoreCase(addSubjectAttributes.exam_pattern)) {
                        weather_subject_exist = true;
                        break;
                    }
                }
                
                if(!weather_subject_exist){
                boolean added_successfully = ServerRequests.addSubject(addSubjectAttributes);
                if (added_successfully) {
                    GUI.libraryInchargeInterfacePanel.showRequestResult("subject added successfully");
                } else {
                    GUI.libraryInchargeInterfacePanel.showRequestResult("subject didn't added, subject might be already added");
                }
                }
                else{
                     GUI.libraryInchargeInterfacePanel.showRequestResult("failed to add subject! subject already exists.");
                }
                
                GUI.libraryInchargeInterfaceFrame.setEnabled(true);
                this.dispose();
            } else if (!enteredAllAttributes) {
                JOptionPane.showMessageDialog(null, "all fields are mandatory");
            } else if (!correctInput) {
                JOptionPane.showMessageDialog(null, "incorrect input");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "invalid number format");
        } catch (IOException ex) {
            Logger.getLogger(AddSubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddSubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        GUI.libraryInchargeInterfacePanel.showRequestResult("subject not added");
        GUI.libraryInchargeInterfaceFrame.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void domainIDComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domainIDComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domainIDComboBoxActionPerformed

    private void yearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearComboBoxActionPerformed

    private void abbreviationTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_abbreviationTextKeyTyped
        if (abbreviationText.getText().length() >= 10) {
            evt.consume();
            messageLabel.setForeground(Color.MAGENTA);
            messageLabel.setText("*maximum charchter length is 10");
        }
    }//GEN-LAST:event_abbreviationTextKeyTyped

    private void abbreviationTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_abbreviationTextKeyReleased
        messageLabel.setForeground(forgroundColor);
        messageLabel.setText("enter details to add subject");
    }//GEN-LAST:event_abbreviationTextKeyReleased

    private void subjectNameTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subjectNameTextKeyTyped
        if (subjectNameText.getText().length() >= 50) {
            evt.consume();
            messageLabel.setForeground(Color.MAGENTA);
            messageLabel.setText("*maximum character length is 50");
        }
    }//GEN-LAST:event_subjectNameTextKeyTyped

    private void subjectNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subjectNameTextKeyReleased
        messageLabel.setForeground(forgroundColor);
        messageLabel.setText("enter details to add subject");
    }//GEN-LAST:event_subjectNameTextKeyReleased

    private void examPatternTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_examPatternTextKeyReleased
        messageLabel.setForeground(forgroundColor);
        messageLabel.setText("enter details to add subject");
    }//GEN-LAST:event_examPatternTextKeyReleased

    private void examPatternTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_examPatternTextKeyTyped
        if (examPatternText.getText().length() >= 20) {
            evt.consume();
            messageLabel.setForeground(Color.MAGENTA);
            messageLabel.setText("*maximum character length is 20");
        }
    }//GEN-LAST:event_examPatternTextKeyTyped

    private void semesterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterComboBoxActionPerformed

    private void abbreviationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abbreviationTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abbreviationTextActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(verifyStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(verifyStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(verifyStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(verifyStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VerifyStudentForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abbreviationLabel;
    private javax.swing.JTextField abbreviationText;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addSubjectLable;
    private javax.swing.JPanel addSubjectPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> domainIDComboBox;
    private javax.swing.JLabel domainIDLabel;
    private javax.swing.JLabel examPatternLabel;
    private javax.swing.JTextField examPatternText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JComboBox<String> semesterComboBox;
    private javax.swing.JLabel semesterLabel;
    private javax.swing.JLabel subjectNameLabel;
    private javax.swing.JTextField subjectNameText;
    private javax.swing.JComboBox<String> yearComboBox;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
