/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import StoragePath.StoragePath;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class EditStoragePathForm extends javax.swing.JFrame {

    /**
     * Creates new form EditStoragePathForm
     */
    private StoragePath storagePath;

    public EditStoragePathForm(StoragePath storagePath) {
        initComponents();
        this.storagePath = storagePath;
        this.storagePathText.setText(storagePath.path);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editStoragePathPanel = new javax.swing.JPanel();
        activityTitleLabel = new javax.swing.JLabel();
        storagePathLabel = new javax.swing.JLabel();
        storagePathText = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        browseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SKNCOECDIS v.18.1 - Departmental Library");

        editStoragePathPanel.setBackground(new java.awt.Color(235, 232, 247));

        activityTitleLabel.setFont(new java.awt.Font("Century Schoolbook", 3, 28)); // NOI18N
        activityTitleLabel.setForeground(new java.awt.Color(131, 56, 209));
        activityTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activityTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64px/Edit.png"))); // NOI18N
        activityTitleLabel.setText("Edit Storage Path");

        storagePathLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        storagePathLabel.setForeground(new java.awt.Color(131, 106, 209));
        storagePathLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        storagePathLabel.setText("Storage Path : ");

        storagePathText.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        storagePathText.setForeground(new java.awt.Color(131, 56, 209));
        storagePathText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 106, 209)));
        storagePathText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storagePathTextActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        saveButton.setForeground(new java.awt.Color(131, 56, 209));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/SaveButton.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(131, 56, 209));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/CancelButton.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        browseButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        browseButton.setForeground(new java.awt.Color(131, 56, 209));
        browseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/StoragePath.png"))); // NOI18N
        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editStoragePathPanelLayout = new javax.swing.GroupLayout(editStoragePathPanel);
        editStoragePathPanel.setLayout(editStoragePathPanelLayout);
        editStoragePathPanelLayout.setHorizontalGroup(
            editStoragePathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStoragePathPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editStoragePathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editStoragePathPanelLayout.createSequentialGroup()
                        .addGap(0, 217, Short.MAX_VALUE)
                        .addComponent(browseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(activityTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(editStoragePathPanelLayout.createSequentialGroup()
                        .addComponent(storagePathLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(storagePathText)))
                .addContainerGap())
        );
        editStoragePathPanelLayout.setVerticalGroup(
            editStoragePathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStoragePathPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activityTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(editStoragePathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storagePathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(storagePathText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editStoragePathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editStoragePathPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editStoragePathPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void storagePathTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storagePathTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storagePathTextActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        this.setAlwaysOnTop(false);
        if (!(storagePathText.getText().equals(""))) {
            String path = storagePathText.getText().trim();
            storagePath.path = path;
            storagePath.path = storagePath.parseStringToPath(storagePath.path);
            if (storagePath.path.equals("INVALID_PATH")) {
                JOptionPane.showMessageDialog(null, "invalid path");
            } else {
                storagePath = StoragePath.saveStoragePath(storagePath);
                if (!storagePath.path.equals("PATH_NOT_SAVED") && !storagePath.path.equals("PATH_NOT_FOUND")) {
                    GUI.libraryInchargeInterfaceFrame.setEnabled(true);
                    GUI.libraryInchargeInterfacePanel.showRequestResult("storage path updated successfully");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "storage path not saved");
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "storage path required to save details");
        }
        this.setAlwaysOnTop(true);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        GUI.libraryInchargeInterfaceFrame.setEnabled(true);
        GUI.libraryInchargeInterfacePanel.showRequestResult("storage path not updated");
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
         jFileChooser.setCurrentDirectory(new java.io.File(".")); // start at application current directory
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnValue=  jFileChooser.showSaveDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectFolder = jFileChooser.getSelectedFile();
          this.storagePathText.setText(selectFolder.getAbsolutePath());
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EditStoragePathForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EditStoragePathForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EditStoragePathForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EditStoragePathForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditStoragePathForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activityTitleLabel;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel editStoragePathPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel storagePathLabel;
    private javax.swing.JTextField storagePathText;
    // End of variables declaration//GEN-END:variables
}
