/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DatabaseAccessObjects.QueryObjects.BookIssueAttributes;
import DatabaseAccessObjects.QueryObjects.UserProfileRequestAttribute;
import DatabaseAccessObjects.ResultObjects.UserProfileQueryResult;
import LibraryIncharge.LibraryInchargeInterface;
import LibraryIncharge.ServerRequests;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class IssueReportForm extends javax.swing.JFrame {

    /**
     * Creates new form IssueReportForm
     */
    public boolean enteredUsername;
    public String username;
    private final String report_id;

    public IssueReportForm(String report_id) {
        initComponents();
        this.report_id = report_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportIssuePanel = new javax.swing.JPanel();
        reportIssueTitleLabel = new javax.swing.JLabel();
        issueBookPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        cancelButoon = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SKNCOECDIS v.18.1 - Departmental Library");
        setResizable(false);

        reportIssuePanel.setBackground(new java.awt.Color(235, 232, 247));

        reportIssueTitleLabel.setFont(new java.awt.Font("Century Schoolbook", 3, 28)); // NOI18N
        reportIssueTitleLabel.setForeground(new java.awt.Color(131, 56, 209));
        reportIssueTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportIssueTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64px/IssueBook.png"))); // NOI18N
        reportIssueTitleLabel.setText("Enter username to issue report");

        issueBookPanel.setBackground(new java.awt.Color(235, 232, 247));

        usernameLabel.setBackground(new java.awt.Color(235, 232, 247));
        usernameLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(131, 56, 209));
        usernameLabel.setText("username :");

        usernameText.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        usernameText.setForeground(new java.awt.Color(131, 106, 209));

        cancelButoon.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cancelButoon.setForeground(new java.awt.Color(131, 56, 209));
        cancelButoon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/CancelButton.png"))); // NOI18N
        cancelButoon.setText("Cancel");
        cancelButoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButoonActionPerformed(evt);
            }
        });

        submitButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(131, 56, 209));
        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/OkayButton.png"))); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 3, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(131, 56, 209));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64px/IssueBook.png"))); // NOI18N
        jLabel2.setText("Enter username to issue report");

        javax.swing.GroupLayout issueBookPanelLayout = new javax.swing.GroupLayout(issueBookPanel);
        issueBookPanel.setLayout(issueBookPanelLayout);
        issueBookPanelLayout.setHorizontalGroup(
            issueBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issueBookPanelLayout.createSequentialGroup()
                .addGroup(issueBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(issueBookPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(usernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(issueBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameText)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, issueBookPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(submitButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButoon)
                                .addGap(8, 8, 8))))
                    .addGroup(issueBookPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)))
                .addContainerGap())
        );
        issueBookPanelLayout.setVerticalGroup(
            issueBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issueBookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(issueBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameText))
                .addGap(18, 18, 18)
                .addGroup(issueBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButoon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout reportIssuePanelLayout = new javax.swing.GroupLayout(reportIssuePanel);
        reportIssuePanel.setLayout(reportIssuePanelLayout);
        reportIssuePanelLayout.setHorizontalGroup(
            reportIssuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportIssuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportIssueTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(reportIssuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(issueBookPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reportIssuePanelLayout.setVerticalGroup(
            reportIssuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportIssuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportIssueTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
            .addGroup(reportIssuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(issueBookPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(reportIssuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(reportIssuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButoonActionPerformed
        enteredUsername = false;
        GUI.libraryInchargeInterfaceFrame.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_cancelButoonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (usernameText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "username can't be empty");
        } else {
            username = usernameText.getText();
            if (username.length() > 16) {
                JOptionPane.showMessageDialog(null, "invalid username length");
            } else {
                try {
                    enteredUsername = true;
                    BookIssueAttributes bookIssueAttributes = new BookIssueAttributes();
                    bookIssueAttributes.username = username;
                    bookIssueAttributes.book_id = report_id;
                    boolean issued_successfully = ServerRequests.issueReport(bookIssueAttributes);
                    if (!issued_successfully) {
                        UserProfileRequestAttribute userProfileRequestAttribute = new UserProfileRequestAttribute();
                        userProfileRequestAttribute.username = username;
                        UserProfileQueryResult user_profile = ServerRequests.getUserProfile(userProfileRequestAttribute);
                        switch (user_profile.user_role) {
                            case "S":
                                if (user_profile.student.verification_status != 1) {
                                    VerifyStudentForm verifyStudentForm = new VerifyStudentForm(user_profile.student, user_profile.has_pending_library_record, false, true, report_id);
                                    verifyStudentForm.setTitle(LibraryInchargeInterface.interfaceFrameTitle);
                                    ImageIcon logo;
                                    logo = new ImageIcon(LibraryInchargeInterface.interfaceFrameImageIconPath);
                                    verifyStudentForm.setIconImage(logo.getImage());
                                    verifyStudentForm.setLocationRelativeTo(null);
                                    verifyStudentForm.pack();
                                    verifyStudentForm.setVisible(true);
                                } else {
                                    GUI.libraryInchargeInterfaceFrame.setEnabled(true);
                                    GUI.libraryInchargeInterfacePanel.showRequestResult("can't issue report !\n report already issued");
                                }
                                break;
                            case "E":
                                if (user_profile.employee.verification_status != 1) {
                                    VerifyEmployeeForm verifyEmployeeForm = new VerifyEmployeeForm(user_profile.employee, user_profile.has_pending_library_record, false, true, report_id);
                                    verifyEmployeeForm.setTitle(LibraryInchargeInterface.interfaceFrameTitle);
                                    ImageIcon logo;
                                    logo = new ImageIcon(getClass().getResource(LibraryInchargeInterface.interfaceFrameImageIconPath));
                                    verifyEmployeeForm.setIconImage(logo.getImage());
                                    verifyEmployeeForm.setLocationRelativeTo(null);
                                    verifyEmployeeForm.pack();
                                    verifyEmployeeForm.setVisible(true);
                                } else {
                                    GUI.libraryInchargeInterfaceFrame.setEnabled(true);
                                    GUI.libraryInchargeInterfacePanel.showRequestResult("can't issue report !\n report already issued");
                                }
                                break;
                            case "NOT_FOUND":
                                GUI.libraryInchargeInterfaceFrame.setEnabled(true);
                                GUI.libraryInchargeInterfacePanel.showRequestResult("invalid username");
                                break;
                            default:
                                break;
                        }
                    } else {
                        GUI.libraryInchargeInterfaceFrame.setEnabled(true);
                        GUI.libraryInchargeInterfacePanel.showRequestResult("report issued successfully");
                    }
                } catch (IOException | ClassNotFoundException ex) {
                    Logger.getLogger(IssueReportForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.dispose();
            }
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(IssueReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(IssueReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(IssueReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(IssueReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new IssueReportForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButoon;
    private javax.swing.JPanel issueBookPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel reportIssuePanel;
    private javax.swing.JLabel reportIssueTitleLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
