/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DatabaseAccessObjects.QueryObjects.ReportReturnAttributes;
import LibraryIncharge.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hp
 */
public class ReturnReportForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginActivity
     */
    ReportReturnAttributes report_return_query = new ReportReturnAttributes();
    int selectedRow = -1;

    public ReturnReportForm(int selectedRow, String username, int report_id, String report_title) {
        initComponents();
        report_return_query.report_id = report_id;
        report_return_query.username = username;
        this.selectedRow = selectedRow;

        usernameLabel.setText("username : " + username);

        if (report_title.length() <= 50) {
            reportDetailsLabel.setText("report : " + report_id + ", " + String.valueOf(report_title.toCharArray(), 0, report_title.length()));
        } else {
            reportDetailsLabel.setText("report : " + report_id + ", " + String.valueOf(report_title.toCharArray(), 0, 50) + " ...");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnReportPanel = new javax.swing.JPanel();
        activityTitleLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        reportDetailsLabel = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SKNCOECDIS v18.1 - Departmental Library");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setResizable(false);

        returnReportPanel.setBackground(new java.awt.Color(235, 232, 247));

        activityTitleLabel.setFont(new java.awt.Font("Century Schoolbook", 3, 28)); // NOI18N
        activityTitleLabel.setForeground(new java.awt.Color(131, 56, 209));
        activityTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activityTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64px/ReturnBook.png"))); // NOI18N
        activityTitleLabel.setText("Return Report");

        usernameLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(131, 106, 209));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        reportDetailsLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        reportDetailsLabel.setForeground(new java.awt.Color(131, 106, 209));
        reportDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        returnButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        returnButton.setForeground(new java.awt.Color(131, 56, 209));
        returnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/ReturnButton.png"))); // NOI18N
        returnButton.setText("Return ");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(131, 56, 209));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/CancelButton.png"))); // NOI18N
        cancelButton.setText("Cancel ");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout returnReportPanelLayout = new javax.swing.GroupLayout(returnReportPanel);
        returnReportPanel.setLayout(returnReportPanelLayout);
        returnReportPanelLayout.setHorizontalGroup(
            returnReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returnReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportDetailsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(activityTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returnReportPanelLayout.createSequentialGroup()
                        .addGap(0, 333, Short.MAX_VALUE)
                        .addComponent(returnButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        returnReportPanelLayout.setVerticalGroup(
            returnReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activityTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportDetailsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(returnReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(returnReportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(returnReportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        try {
            GUI.libraryInchargeInterfaceFrame.setEnabled(true);
            GUI.libraryInchargeInterfacePanel.showRequestResult(ServerRequests.returnReport(report_return_query));
            GUI.libraryInchargeInterfacePanel.removeRowFromTable(4, selectedRow);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(ReturnReportForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_returnButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        GUI.libraryInchargeInterfaceFrame.setEnabled(true);
        GUI.libraryInchargeInterfacePanel.showRequestResult("report didn't return");
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ReturnReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ReturnReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ReturnReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ReturnReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new EditConnectionForm().setVisible(true);
////                
////            }
////        });
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new EditConnectionForm().setVisible(true);
////                
////            }
////        });
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new EditConnectionForm().setVisible(true);
////                
////            }
////        });
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new EditConnectionForm().setVisible(true);
////                
////            }
////        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activityTitleLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel reportDetailsLabel;
    private javax.swing.JButton returnButton;
    private javax.swing.JPanel returnReportPanel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
