/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DatabaseAccessObjects.QueryObjects.AddSubjectAttributes;
import DatabaseAccessObjects.ResultObjects.DomainQueryResult;
import DatabaseAccessObjects.ResultObjects.SubjectQueryResult;
import LibraryIncharge.ServerRequests;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class UpdateSubjectForm extends javax.swing.JFrame {

    /**
     * Creates new form verifyStudentForm
     */
    boolean correctInput = true;
    Color forgroundColor = new Color(131, 56, 209);
    Color backgroundColor=new Color(235, 232, 247);
    List<SubjectQueryResult> subjectQueryResultList=new ArrayList<>();
    List<DomainQueryResult> domainQueryResultsList=new ArrayList<>();
  

    public UpdateSubjectForm(List<SubjectQueryResult> subjectQueryResultList, List<DomainQueryResult> domainQueryResultList) {
        initComponents();
        this.subjectQueryResultList=subjectQueryResultList;
        this.domainQueryResultsList=domainQueryResultList;
        
        domainIDComboBox.removeAllItems();
        for (int i = 0; i < domainQueryResultList.size(); i++) {
            domainIDComboBox.addItem(domainQueryResultList.get(i).domain_id + " : " + domainQueryResultList.get(i).domain_name);
        }
        domainIDComboBox.setSelectedIndex(-1);
        domainIDComboBox.setForeground(forgroundColor);
        domainIDComboBox.setBackground(backgroundColor);
        
        selectSubjectIDComboBox.removeAllItems();
        for (int i = 0; i < subjectQueryResultList.size(); i++) {
            selectSubjectIDComboBox.addItem(subjectQueryResultList.get(i).subject_name);
        }
        selectSubjectIDComboBox.setSelectedIndex(-1);
        selectSubjectIDComboBox.setForeground(forgroundColor);
        selectSubjectIDComboBox.setBackground(backgroundColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateSubjectPanel = new javax.swing.JPanel();
        updateSubjectLable = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        selectSubjectIDComboBox = new javax.swing.JComboBox<>();
        subjectIDLabel = new javax.swing.JLabel();
        subjectIDText = new javax.swing.JTextField();
        selectSubjectLabel = new javax.swing.JLabel();
        subjectNameLabel = new javax.swing.JLabel();
        subjectNameText = new javax.swing.JTextField();
        abbreviationLabel = new javax.swing.JLabel();
        abbreviationText = new javax.swing.JTextField();
        semesterLabel = new javax.swing.JLabel();
        semesterComboBox = new javax.swing.JComboBox<>();
        yearLabel = new javax.swing.JLabel();
        yearComboBox = new javax.swing.JComboBox<>();
        examPatternLabel = new javax.swing.JLabel();
        examPatternText = new javax.swing.JTextField();
        domainIDLabel = new javax.swing.JLabel();
        domainIDComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SKNCOECDIS v.18.1 - Departmental Library");
        setResizable(false);

        updateSubjectPanel.setBackground(new java.awt.Color(235, 232, 247));

        updateSubjectLable.setFont(new java.awt.Font("Century Schoolbook", 3, 28)); // NOI18N
        updateSubjectLable.setForeground(new java.awt.Color(131, 56, 209));
        updateSubjectLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateSubjectLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64px/Edit2.png"))); // NOI18N
        updateSubjectLable.setText("Update Subject");

        messageLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(131, 56, 209));
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText("select & update subject");

        cancelButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(131, 56, 209));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/CancelButton.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        updateButton.setForeground(new java.awt.Color(131, 56, 209));
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/UpdateButton.png"))); // NOI18N
        updateButton.setText("Update");
        updateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        selectSubjectIDComboBox.setBackground(new java.awt.Color(235, 232, 247));
        selectSubjectIDComboBox.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        selectSubjectIDComboBox.setForeground(new java.awt.Color(131, 106, 209));
        selectSubjectIDComboBox.setToolTipText("");
        selectSubjectIDComboBox.setAutoscrolls(true);
        selectSubjectIDComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectSubjectIDComboBoxItemStateChanged(evt);
            }
        });
        selectSubjectIDComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                selectSubjectIDComboBoxMousePressed(evt);
            }
        });
        selectSubjectIDComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSubjectIDComboBoxActionPerformed(evt);
            }
        });
        selectSubjectIDComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                selectSubjectIDComboBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                selectSubjectIDComboBoxKeyTyped(evt);
            }
        });

        subjectIDLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        subjectIDLabel.setForeground(new java.awt.Color(131, 56, 209));
        subjectIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subjectIDLabel.setText("subject id : ");

        subjectIDText.setEditable(false);
        subjectIDText.setBackground(new java.awt.Color(235, 232, 247));
        subjectIDText.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        subjectIDText.setForeground(new java.awt.Color(131, 106, 209));
        subjectIDText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 106, 209)));
        subjectIDText.setSelectionColor(new java.awt.Color(203, 192, 235));
        subjectIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectIDTextActionPerformed(evt);
            }
        });
        subjectIDText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                subjectIDTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                subjectIDTextKeyTyped(evt);
            }
        });

        selectSubjectLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        selectSubjectLabel.setForeground(new java.awt.Color(131, 56, 209));
        selectSubjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        selectSubjectLabel.setText("select subject : ");

        subjectNameLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        subjectNameLabel.setForeground(new java.awt.Color(131, 56, 209));
        subjectNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subjectNameLabel.setText("subject name : ");

        subjectNameText.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        subjectNameText.setForeground(new java.awt.Color(131, 106, 209));
        subjectNameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 106, 209)));
        subjectNameText.setSelectionColor(new java.awt.Color(203, 192, 235));
        subjectNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                subjectNameTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                subjectNameTextKeyTyped(evt);
            }
        });

        abbreviationLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        abbreviationLabel.setForeground(new java.awt.Color(131, 56, 209));
        abbreviationLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        abbreviationLabel.setText("abbreviation : ");

        abbreviationText.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        abbreviationText.setForeground(new java.awt.Color(131, 106, 209));
        abbreviationText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 106, 209)));
        abbreviationText.setSelectionColor(new java.awt.Color(203, 192, 235));
        abbreviationText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                abbreviationTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                abbreviationTextKeyTyped(evt);
            }
        });

        semesterLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        semesterLabel.setForeground(new java.awt.Color(131, 56, 209));
        semesterLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        semesterLabel.setText("semester : ");

        semesterComboBox.setBackground(new java.awt.Color(235, 232, 247));
        semesterComboBox.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        semesterComboBox.setForeground(new java.awt.Color(131, 106, 209));
        semesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        semesterComboBox.setSelectedIndex(-1);
        semesterComboBox.setToolTipText("");
        semesterComboBox.setAutoscrolls(true);
        semesterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterComboBoxActionPerformed(evt);
            }
        });

        yearLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(131, 56, 209));
        yearLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yearLabel.setText("year : ");

        yearComboBox.setBackground(new java.awt.Color(235, 232, 247));
        yearComboBox.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        yearComboBox.setForeground(new java.awt.Color(131, 106, 209));
        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FE", "SE", "TE", "BE" }));
        yearComboBox.setSelectedIndex(-1);
        yearComboBox.setToolTipText("");
        yearComboBox.setAutoscrolls(true);
        yearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboBoxActionPerformed(evt);
            }
        });

        examPatternLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        examPatternLabel.setForeground(new java.awt.Color(131, 56, 209));
        examPatternLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        examPatternLabel.setText("exam pattern : ");

        examPatternText.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        examPatternText.setForeground(new java.awt.Color(131, 106, 209));
        examPatternText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 106, 209)));
        examPatternText.setSelectionColor(new java.awt.Color(203, 192, 235));
        examPatternText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                examPatternTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                examPatternTextKeyTyped(evt);
            }
        });

        domainIDLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        domainIDLabel.setForeground(new java.awt.Color(131, 56, 209));
        domainIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        domainIDLabel.setText("domain id : ");

        domainIDComboBox.setBackground(new java.awt.Color(235, 232, 247));
        domainIDComboBox.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        domainIDComboBox.setForeground(new java.awt.Color(131, 106, 209));
        domainIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        domainIDComboBox.setSelectedIndex(-1);
        domainIDComboBox.setToolTipText("");
        domainIDComboBox.setAutoscrolls(true);
        domainIDComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domainIDComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateSubjectPanelLayout = new javax.swing.GroupLayout(updateSubjectPanel);
        updateSubjectPanel.setLayout(updateSubjectPanelLayout);
        updateSubjectPanelLayout.setHorizontalGroup(
            updateSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateSubjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateSubjectLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(updateSubjectPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(updateSubjectPanelLayout.createSequentialGroup()
                        .addGroup(updateSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(selectSubjectLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subjectIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updateSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectSubjectIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subjectIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(updateSubjectPanelLayout.createSequentialGroup()
                        .addGroup(updateSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(examPatternLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(semesterLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(abbreviationLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(yearLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(domainIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(subjectNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updateSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectNameText)
                            .addComponent(abbreviationText)
                            .addComponent(examPatternText, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(domainIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        updateSubjectPanelLayout.setVerticalGroup(
            updateSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateSubjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateSubjectLable, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(updateSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectSubjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectSubjectIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(updateSubjectPanelLayout.createSequentialGroup()
                        .addComponent(examPatternText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(updateSubjectPanelLayout.createSequentialGroup()
                        .addComponent(subjectNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abbreviationText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(domainIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, updateSubjectPanelLayout.createSequentialGroup()
                        .addComponent(subjectNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abbreviationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(semesterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(examPatternLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(domainIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(updateSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateSubjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateSubjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        boolean enteredAllAttributes = true;
        AddSubjectAttributes addSubjectAttributes = new AddSubjectAttributes();
        try {
            if(!subjectIDText.getText().equals("")){
                addSubjectAttributes.subject_id=Integer.parseInt(subjectIDText.getText());
            }
            else{
                enteredAllAttributes=false;
            }
            if(!subjectNameText.getText().equals("")){
                addSubjectAttributes.subject_name=subjectNameText.getText();
            }
            else{
                enteredAllAttributes=false;
            }
            if (!abbreviationText.getText().equals("")) {
                addSubjectAttributes.subject_abbreviation = abbreviationText.getText();
            } else {
                enteredAllAttributes = false;
            }

            if (semesterComboBox.getSelectedIndex() > -1) {
                addSubjectAttributes.semester = semesterComboBox.getSelectedItem().toString();
            } else {
                enteredAllAttributes = false;
            }

            if (yearComboBox.getSelectedIndex() > -1) {
                addSubjectAttributes.academic_year = yearComboBox.getSelectedItem().toString();
            } else {
                enteredAllAttributes = false;
            }

            if (!examPatternText.getText().equals("")) {
                addSubjectAttributes.exam_pattern = examPatternText.getText();
            }

            if (domainIDComboBox.getSelectedIndex() > -1) {
                addSubjectAttributes.domain_id = Integer.parseInt(String.valueOf(domainIDComboBox.getSelectedItem().toString().toCharArray(), 0, domainIDComboBox.getSelectedItem().toString().indexOf(':') - 1));
            } else {
                enteredAllAttributes = false;
            }
          
            if (enteredAllAttributes && correctInput) {
                boolean added_successfully = ServerRequests.updateSubject(addSubjectAttributes);
                if (added_successfully) {
                    GUI.libraryInchargeInterfacePanel.showRequestResult("subject updated successfully");
                } else {
                    GUI.libraryInchargeInterfacePanel.showRequestResult("subject didn't updated, updated subject name might be already present");
                }
                GUI.libraryInchargeInterfaceFrame.setEnabled(true);
                this.dispose();
            } else if (!enteredAllAttributes) {
                JOptionPane.showMessageDialog(null, "all fields are mandatory");
            } else if (!correctInput) {
                JOptionPane.showMessageDialog(null, "incorrect input");
            }
        } catch (NumberFormatException e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, "invalid number format");
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(UpdateSubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        GUI.libraryInchargeInterfacePanel.showRequestResult("subject not updated");
        GUI.libraryInchargeInterfaceFrame.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void subjectIDTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subjectIDTextKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectIDTextKeyReleased

    private void subjectIDTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subjectIDTextKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectIDTextKeyTyped

    private void subjectIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectIDTextActionPerformed

    private void selectSubjectIDComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSubjectIDComboBoxActionPerformed
         int selectedIndex=selectSubjectIDComboBox.getSelectedIndex();
        if(selectedIndex>-1){
            subjectIDText.setText(String.valueOf(subjectQueryResultList.get(selectedIndex).subject_id));
            subjectNameText.setText(String.valueOf(subjectQueryResultList.get(selectedIndex).subject_name));
            abbreviationText.setText(String.valueOf(subjectQueryResultList.get(selectedIndex).subject_abbreviation));
            examPatternText.setText(subjectQueryResultList.get(selectedIndex).exam_pattern);
            
            semesterComboBox.setSelectedIndex(Integer.parseInt(subjectQueryResultList.get(selectedIndex).semester)-1);
            
           String year=subjectQueryResultList.get(selectedIndex).academic_year;
             switch (year) {
                 case "FE":
                     yearComboBox.setSelectedIndex(0);
                     break;
                 case "SE":
                     yearComboBox.setSelectedIndex(1);
                     break;
                 case "TE":
                     yearComboBox.setSelectedIndex(2);
                     break;
                 default:
                     yearComboBox.setSelectedIndex(3);
                     break;
             }
             for(int i=0;i<domainQueryResultsList.size();i++){
                 if(domainQueryResultsList.get(i).domain_id==subjectQueryResultList.get(selectedIndex).domain_id){
                   domainIDComboBox.setSelectedIndex(i);
                   break;
                 }
             }
        }
        else{
            subjectIDText.setText("");
            subjectNameText.setText("");
             abbreviationText.setText("");
             semesterComboBox.setSelectedIndex(-1);
             yearComboBox.setSelectedIndex(-1);
             examPatternText.setText("");
            domainIDComboBox.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_selectSubjectIDComboBoxActionPerformed

    private void selectSubjectIDComboBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_selectSubjectIDComboBoxKeyReleased

    }//GEN-LAST:event_selectSubjectIDComboBoxKeyReleased

    private void selectSubjectIDComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectSubjectIDComboBoxItemStateChanged
        
    }//GEN-LAST:event_selectSubjectIDComboBoxItemStateChanged

    private void selectSubjectIDComboBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectSubjectIDComboBoxMousePressed
        
    }//GEN-LAST:event_selectSubjectIDComboBoxMousePressed

    private void selectSubjectIDComboBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_selectSubjectIDComboBoxKeyTyped

    }//GEN-LAST:event_selectSubjectIDComboBoxKeyTyped

    private void subjectNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subjectNameTextKeyReleased
        messageLabel.setForeground(forgroundColor);
        messageLabel.setText("select & update subject");
    }//GEN-LAST:event_subjectNameTextKeyReleased

    private void subjectNameTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subjectNameTextKeyTyped
        if (subjectNameText.getText().length() >= 50) {
            evt.consume();
            messageLabel.setForeground(Color.MAGENTA);
            messageLabel.setText("*maximum character length is 50");
        }
    }//GEN-LAST:event_subjectNameTextKeyTyped

    private void abbreviationTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_abbreviationTextKeyReleased
        messageLabel.setForeground(forgroundColor);
        messageLabel.setText("select & update subject");
    }//GEN-LAST:event_abbreviationTextKeyReleased

    private void abbreviationTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_abbreviationTextKeyTyped
        if (abbreviationText.getText().length() >= 5) {
            evt.consume();
            messageLabel.setForeground(Color.MAGENTA);
            messageLabel.setText("*maximum charchter length is 5");
        }
    }//GEN-LAST:event_abbreviationTextKeyTyped

    private void semesterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterComboBoxActionPerformed

    private void yearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearComboBoxActionPerformed

    private void examPatternTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_examPatternTextKeyReleased
        messageLabel.setForeground(forgroundColor);
        messageLabel.setText("select & update subject");
    }//GEN-LAST:event_examPatternTextKeyReleased

    private void examPatternTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_examPatternTextKeyTyped
        if (examPatternText.getText().length() >= 20) {
            evt.consume();
            messageLabel.setForeground(Color.MAGENTA);
            messageLabel.setText("*maximum character length is 20");
        }
    }//GEN-LAST:event_examPatternTextKeyTyped

    private void domainIDComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domainIDComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domainIDComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(verifyStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(verifyStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(verifyStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(verifyStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VerifyStudentForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abbreviationLabel;
    private javax.swing.JTextField abbreviationText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> domainIDComboBox;
    private javax.swing.JLabel domainIDLabel;
    private javax.swing.JLabel examPatternLabel;
    private javax.swing.JTextField examPatternText;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JComboBox<String> selectSubjectIDComboBox;
    private javax.swing.JLabel selectSubjectLabel;
    private javax.swing.JComboBox<String> semesterComboBox;
    private javax.swing.JLabel semesterLabel;
    private javax.swing.JLabel subjectIDLabel;
    private javax.swing.JTextField subjectIDText;
    private javax.swing.JLabel subjectNameLabel;
    private javax.swing.JTextField subjectNameText;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel updateSubjectLable;
    private javax.swing.JPanel updateSubjectPanel;
    private javax.swing.JComboBox<String> yearComboBox;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
