/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DatabaseAccessObjects.QueryObjects.AddDomainAttributes;
import DatabaseAccessObjects.ResultObjects.DomainQueryResult;
import LibraryIncharge.ServerRequests;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class UpdateDomainForm extends javax.swing.JFrame {

    /**
     * Creates new form verifyStudentForm
     */
    boolean correctInput = true;
    Color forgroundColor = new Color(131, 56, 209);
    Color backgroundColor=new Color(235, 232, 247);
     List<DomainQueryResult> domainQueryResultsList=new ArrayList<>();
  

    public UpdateDomainForm(List<DomainQueryResult> domainQueryResultList) {
        initComponents();
        this.domainQueryResultsList=domainQueryResultList;
        selectDomainIDComboBox.removeAllItems();
        for (int i = 0; i < domainQueryResultList.size(); i++) {
            selectDomainIDComboBox.addItem(domainQueryResultList.get(i).domain_name);
        }
        selectDomainIDComboBox.setSelectedIndex(-1);
        selectDomainIDComboBox.setForeground(forgroundColor);
        selectDomainIDComboBox.setBackground(backgroundColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateDomainTitlePanel = new javax.swing.JPanel();
        updateDomainTitleLable = new javax.swing.JLabel();
        domainNameLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        domainNameText = new javax.swing.JTextField();
        selectDomainIDComboBox = new javax.swing.JComboBox<>();
        domainIDLabel = new javax.swing.JLabel();
        domainIDText = new javax.swing.JTextField();
        selectDomainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SKNCOECDIS v.18.1 - Departmental Library");
        setResizable(false);

        updateDomainTitlePanel.setBackground(new java.awt.Color(235, 232, 247));

        updateDomainTitleLable.setFont(new java.awt.Font("Century Schoolbook", 3, 28)); // NOI18N
        updateDomainTitleLable.setForeground(new java.awt.Color(131, 56, 209));
        updateDomainTitleLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateDomainTitleLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64px/Edit2.png"))); // NOI18N
        updateDomainTitleLable.setText("Update Domain");

        domainNameLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        domainNameLabel.setForeground(new java.awt.Color(131, 56, 209));
        domainNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        domainNameLabel.setText("domain name : ");

        messageLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(131, 56, 209));
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText("select & update domain");

        cancelButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(131, 56, 209));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/CancelButton.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        updateButton.setForeground(new java.awt.Color(131, 56, 209));
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/UpdateButton.png"))); // NOI18N
        updateButton.setText("Update");
        updateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        domainNameText.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        domainNameText.setForeground(new java.awt.Color(131, 106, 209));
        domainNameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 106, 209)));
        domainNameText.setSelectionColor(new java.awt.Color(203, 192, 235));
        domainNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                domainNameTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                domainNameTextKeyTyped(evt);
            }
        });

        selectDomainIDComboBox.setBackground(new java.awt.Color(235, 232, 247));
        selectDomainIDComboBox.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        selectDomainIDComboBox.setForeground(new java.awt.Color(131, 106, 209));
        selectDomainIDComboBox.setToolTipText("");
        selectDomainIDComboBox.setAutoscrolls(true);
        selectDomainIDComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectDomainIDComboBoxItemStateChanged(evt);
            }
        });
        selectDomainIDComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                selectDomainIDComboBoxMousePressed(evt);
            }
        });
        selectDomainIDComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDomainIDComboBoxActionPerformed(evt);
            }
        });
        selectDomainIDComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                selectDomainIDComboBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                selectDomainIDComboBoxKeyTyped(evt);
            }
        });

        domainIDLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        domainIDLabel.setForeground(new java.awt.Color(131, 56, 209));
        domainIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        domainIDLabel.setText("domain id : ");

        domainIDText.setEditable(false);
        domainIDText.setBackground(new java.awt.Color(235, 232, 247));
        domainIDText.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        domainIDText.setForeground(new java.awt.Color(131, 106, 209));
        domainIDText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 106, 209)));
        domainIDText.setSelectionColor(new java.awt.Color(203, 192, 235));
        domainIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domainIDTextActionPerformed(evt);
            }
        });
        domainIDText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                domainIDTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                domainIDTextKeyTyped(evt);
            }
        });

        selectDomainLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        selectDomainLabel.setForeground(new java.awt.Color(131, 56, 209));
        selectDomainLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        selectDomainLabel.setText("select domain : ");

        javax.swing.GroupLayout updateDomainTitlePanelLayout = new javax.swing.GroupLayout(updateDomainTitlePanel);
        updateDomainTitlePanel.setLayout(updateDomainTitlePanelLayout);
        updateDomainTitlePanelLayout.setHorizontalGroup(
            updateDomainTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateDomainTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateDomainTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateDomainTitleLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateDomainTitlePanelLayout.createSequentialGroup()
                        .addComponent(domainNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(domainNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updateDomainTitlePanelLayout.createSequentialGroup()
                        .addGroup(updateDomainTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(selectDomainLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(domainIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updateDomainTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectDomainIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(domainIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateDomainTitlePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        updateDomainTitlePanelLayout.setVerticalGroup(
            updateDomainTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateDomainTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateDomainTitleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(updateDomainTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDomainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectDomainIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateDomainTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(domainIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(domainIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateDomainTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(domainNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(domainNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updateDomainTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateDomainTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateDomainTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
       boolean enteredAllAttributes = true;
        AddDomainAttributes addDomainAttributes = new AddDomainAttributes();
        try {
            if(!domainIDText.getText().equals("")){
                addDomainAttributes.domain_id=Integer.parseInt(domainIDText.getText());
            }
            else{
                enteredAllAttributes=false;
            }
            if (!domainNameText.getText().equals("")) {
                addDomainAttributes.domain_name = domainNameText.getText();
            } else {
                enteredAllAttributes = false;
            }
            
            if (enteredAllAttributes && correctInput) {
                boolean updated_successfully;
                updated_successfully = ServerRequests.updateDomain(addDomainAttributes);
                if (updated_successfully) {
                    GUI.libraryInchargeInterfacePanel.showRequestResult("domain updated successfully");
                } else {
                    GUI.libraryInchargeInterfacePanel.showRequestResult("domain didn't updated, updated domain name might be already present");
                }
                GUI.libraryInchargeInterfaceFrame.setEnabled(true);
                this.dispose();
            } else if (!enteredAllAttributes) {
                JOptionPane.showMessageDialog(null, "all fields are mandatory");
            } else if (!correctInput) {
                JOptionPane.showMessageDialog(null, "incorrect input");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "invalid number format");
        } catch (IOException ex) {
            Logger.getLogger(AddReportTitleForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpdateDomainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        GUI.libraryInchargeInterfacePanel.showRequestResult("domain not updated");
        GUI.libraryInchargeInterfaceFrame.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void domainNameTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_domainNameTextKeyTyped
        if (domainNameText.getText().length() >= 100) {
            evt.consume();
            messageLabel.setForeground(Color.MAGENTA);
            messageLabel.setText("*maximum charchter length is 100");
        }
    }//GEN-LAST:event_domainNameTextKeyTyped

    private void domainNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_domainNameTextKeyReleased
        messageLabel.setForeground(forgroundColor);
        messageLabel.setText("select & update domain");
    }//GEN-LAST:event_domainNameTextKeyReleased

    private void domainIDTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_domainIDTextKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_domainIDTextKeyReleased

    private void domainIDTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_domainIDTextKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_domainIDTextKeyTyped

    private void domainIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domainIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domainIDTextActionPerformed

    private void selectDomainIDComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDomainIDComboBoxActionPerformed
         int selectedIndex=selectDomainIDComboBox.getSelectedIndex();
        if(selectedIndex>-1){
            domainIDText.setText(String.valueOf(domainQueryResultsList.get(selectedIndex).domain_id));
            domainNameText.setText(String.valueOf(domainQueryResultsList.get(selectedIndex).domain_name));
        }
        else{
            domainIDText.setText("");
            domainNameText.setText("");
        }
    }//GEN-LAST:event_selectDomainIDComboBoxActionPerformed

    private void selectDomainIDComboBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_selectDomainIDComboBoxKeyReleased

    }//GEN-LAST:event_selectDomainIDComboBoxKeyReleased

    private void selectDomainIDComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectDomainIDComboBoxItemStateChanged
        
    }//GEN-LAST:event_selectDomainIDComboBoxItemStateChanged

    private void selectDomainIDComboBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectDomainIDComboBoxMousePressed
        
    }//GEN-LAST:event_selectDomainIDComboBoxMousePressed

    private void selectDomainIDComboBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_selectDomainIDComboBoxKeyTyped

    }//GEN-LAST:event_selectDomainIDComboBoxKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(verifyStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(verifyStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(verifyStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(verifyStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VerifyStudentForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel domainIDLabel;
    private javax.swing.JTextField domainIDText;
    private javax.swing.JLabel domainNameLabel;
    private javax.swing.JTextField domainNameText;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JComboBox<String> selectDomainIDComboBox;
    private javax.swing.JLabel selectDomainLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel updateDomainTitleLable;
    private javax.swing.JPanel updateDomainTitlePanel;
    // End of variables declaration//GEN-END:variables
}
