/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DatabaseAccessObjects.QueryObjects.BookIssueAttributes;
import DatabaseAccessObjects.QueryObjects.Student;
import DatabaseAccessObjects.ResultObjects.UserProfileQueryResult;
import LibraryIncharge.ServerRequests;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hp
 */
public class VerifyStudentForm extends javax.swing.JFrame {

    /**
     * Creates new form verifyStudentForm
     */
    Student student;
    boolean has_pending_record;
    boolean alsoIssueBook;
    boolean alsoIssueReport;
    String book_or_report_id;

    public VerifyStudentForm(Student student, boolean has_pending_record, boolean alsoIssueBook, boolean alsoIssueReport, String book_or_report_id) {
        initComponents();
        this.student = student;
        this.has_pending_record = has_pending_record;
        this.alsoIssueBook = alsoIssueBook;
        this.alsoIssueReport = alsoIssueReport;
        this.book_or_report_id = book_or_report_id;
        usernameLabel.setText(student.username);
        firstNameLabel.setText(student.first_name);
        lastNameLabel.setText(student.last_name);
        emailLabel.setText(student.email);
        mobileNoLabel.setText(student.mobile_no);
        uniqueIDLabel.setText(student.unique_id);
        academicYearLabel.setText(student.academic_year);
        divisionLabel.setText(student.division);
        if (student.verification_status == 1) {
            verificationLabel.setText("Verified");
        } else {
            verificationLabel.setText("Not Verified");
        }
        if (has_pending_record) {
            pendingRecordsLabel.setText("Yes");
        } else {
            pendingRecordsLabel.setText("No");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verifyStudentPanel = new javax.swing.JPanel();
        verifyStudentTitleLable = new javax.swing.JLabel();
        slastNameLabel = new javax.swing.JLabel();
        susernameLabel = new javax.swing.JLabel();
        sfirstNameLabel = new javax.swing.JLabel();
        smobileNoLabel = new javax.swing.JLabel();
        semailLabel = new javax.swing.JLabel();
        spendingRecordsLabel = new javax.swing.JLabel();
        sverificationLabel = new javax.swing.JLabel();
        sacademicYearLabel = new javax.swing.JLabel();
        suniqueIDLabel = new javax.swing.JLabel();
        sdivisionLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        uniqueIDLabel = new javax.swing.JLabel();
        verificationLabel = new javax.swing.JLabel();
        divisionLabel = new javax.swing.JLabel();
        academicYearLabel = new javax.swing.JLabel();
        pendingRecordsLabel = new javax.swing.JLabel();
        mobileNoLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        verifyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SKNCOECDIS v.18.1 - Departmental Library");
        setResizable(false);

        verifyStudentPanel.setBackground(new java.awt.Color(235, 232, 247));

        verifyStudentTitleLable.setFont(new java.awt.Font("Century Schoolbook", 3, 28)); // NOI18N
        verifyStudentTitleLable.setForeground(new java.awt.Color(131, 56, 209));
        verifyStudentTitleLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verifyStudentTitleLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64px/User.png"))); // NOI18N
        verifyStudentTitleLable.setText("Verify Student Details");

        slastNameLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        slastNameLabel.setForeground(new java.awt.Color(131, 56, 209));
        slastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        slastNameLabel.setText("last name : ");

        susernameLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        susernameLabel.setForeground(new java.awt.Color(131, 56, 209));
        susernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        susernameLabel.setText("username : ");

        sfirstNameLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        sfirstNameLabel.setForeground(new java.awt.Color(131, 56, 209));
        sfirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sfirstNameLabel.setText("first name : ");

        smobileNoLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        smobileNoLabel.setForeground(new java.awt.Color(131, 56, 209));
        smobileNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        smobileNoLabel.setText("mobile no : ");

        semailLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        semailLabel.setForeground(new java.awt.Color(131, 56, 209));
        semailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        semailLabel.setText("email : ");

        spendingRecordsLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        spendingRecordsLabel.setForeground(new java.awt.Color(131, 56, 209));
        spendingRecordsLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        spendingRecordsLabel.setText("pending records : ");

        sverificationLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        sverificationLabel.setForeground(new java.awt.Color(131, 56, 209));
        sverificationLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sverificationLabel.setText("verification : ");

        sacademicYearLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        sacademicYearLabel.setForeground(new java.awt.Color(131, 56, 209));
        sacademicYearLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sacademicYearLabel.setText("academic year : ");

        suniqueIDLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        suniqueIDLabel.setForeground(new java.awt.Color(131, 56, 209));
        suniqueIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        suniqueIDLabel.setText("unique id : ");

        sdivisionLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        sdivisionLabel.setForeground(new java.awt.Color(131, 56, 209));
        sdivisionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sdivisionLabel.setText("division : ");

        firstNameLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(131, 106, 209));

        usernameLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(131, 106, 209));

        uniqueIDLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        uniqueIDLabel.setForeground(new java.awt.Color(131, 106, 209));

        verificationLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        verificationLabel.setForeground(new java.awt.Color(131, 106, 209));

        divisionLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        divisionLabel.setForeground(new java.awt.Color(131, 106, 209));

        academicYearLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        academicYearLabel.setForeground(new java.awt.Color(131, 106, 209));

        pendingRecordsLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        pendingRecordsLabel.setForeground(new java.awt.Color(131, 106, 209));

        mobileNoLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        mobileNoLabel.setForeground(new java.awt.Color(131, 106, 209));

        emailLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(131, 106, 209));

        lastNameLabel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(131, 106, 209));

        cancelButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(131, 56, 209));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/CancelButton.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        verifyButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        verifyButton.setForeground(new java.awt.Color(131, 56, 209));
        verifyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32px/OkayButton.png"))); // NOI18N
        verifyButton.setText("Verify");
        verifyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        verifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout verifyStudentPanelLayout = new javax.swing.GroupLayout(verifyStudentPanel);
        verifyStudentPanel.setLayout(verifyStudentPanelLayout);
        verifyStudentPanelLayout.setHorizontalGroup(
            verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verifyStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verifyStudentTitleLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(verifyStudentPanelLayout.createSequentialGroup()
                        .addGroup(verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sdivisionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(spendingRecordsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(susernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sacademicYearLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(suniqueIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(smobileNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(semailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(slastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sfirstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(sverificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uniqueIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(verificationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(divisionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(academicYearLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pendingRecordsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mobileNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verifyStudentPanelLayout.createSequentialGroup()
                                .addGap(0, 129, Short.MAX_VALUE)
                                .addComponent(verifyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton)))))
                .addContainerGap())
        );
        verifyStudentPanelLayout.setVerticalGroup(
            verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verifyStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verifyStudentTitleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(susernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sfirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smobileNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suniqueIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uniqueIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sacademicYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(academicYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdivisionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sverificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spendingRecordsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pendingRecordsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(verifyStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(verifyStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(verifyStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyButtonActionPerformed
        try {
            // TODO add your handling code here:
            if(!student.academic_year.equals("PO")){
            UserProfileQueryResult user_profile_query = new UserProfileQueryResult();
            user_profile_query.user_role = "S";
            user_profile_query.student = student;
            user_profile_query.has_pending_library_record = has_pending_record;
            String resultFromVerification = ServerRequests.verifyUserProfile(user_profile_query);
            if (alsoIssueBook) {
                GUI.libraryInchargeInterfaceFrame.setEnabled(true);
                switch (resultFromVerification) {
                    case "VERIFIED_SUCCESSFULLY":
                        BookIssueAttributes book_issue_query = new BookIssueAttributes();
                        book_issue_query.book_id = book_or_report_id;
                        book_issue_query.username = student.username;
                        String date_of_return = ServerRequests.issueBook(book_issue_query);
                        if (date_of_return.equals("NOT_ISSUED")) {
                            GUI.libraryInchargeInterfacePanel.showRequestResult("book didn't issued");
                        } else {
                            GUI.libraryInchargeInterfacePanel.showRequestResult("book issued successfully, date of return : " + date_of_return);
                        }
                        break;
                    case "HAS_PENDING_RECORD":
                        GUI.libraryInchargeInterfacePanel.showRequestResult("book didn't issued, user has pending records");
                        break;
                    case "NOT_VERIFIED":
                        GUI.libraryInchargeInterfacePanel.showRequestResult("book didn't issued");
                        break;
                    case "ALREADY_VERIFIED":
                        GUI.libraryInchargeInterfacePanel.showRequestResult("can't issue book!  \n maximum books reached or same book already issued ");
                    break;
                    default:
                        GUI.libraryInchargeInterfacePanel.showRequestResult(resultFromVerification);
                        break;
                }
            } else if (alsoIssueReport) {
                GUI.libraryInchargeInterfaceFrame.setEnabled(true);
                switch (resultFromVerification) {
                    case "VERIFIED_SUCCESSFULLY":
                        BookIssueAttributes book_issue_query = new BookIssueAttributes();
                        book_issue_query.book_id = book_or_report_id;
                        book_issue_query.username = student.username;
                        boolean issued_successfully = ServerRequests.issueReport(book_issue_query);
                        if (!issued_successfully) {
                            GUI.libraryInchargeInterfacePanel.showRequestResult("report didn't issued");
                        } else {
                            GUI.libraryInchargeInterfacePanel.showRequestResult("report issued successfully");
                        }
                        break;
                    case "HAS_PENDING_RECORD":
                        GUI.libraryInchargeInterfacePanel.showRequestResult("report didn't issued, user has pending record");
                        break;
                    case "NOT_VERIFIED":
                        GUI.libraryInchargeInterfacePanel.showRequestResult("user profile not verified");
                        break;
                    case "ALREADY_VERIFIED":
                        GUI.libraryInchargeInterfacePanel.showRequestResult("can't issue report !\n report already issued");
                    break;
                    default:
                        GUI.libraryInchargeInterfacePanel.showRequestResult(resultFromVerification);
                        break;
                }
            } else {
                GUI.libraryInchargeInterfaceFrame.setEnabled(true);
                switch (resultFromVerification) {
                    case "VERIFIED_SUCCESSFULLY":
                        GUI.libraryInchargeInterfacePanel.showRequestResult("user profile verified successfully");
                        break;
                    case "HAS_PENDING_RECORD":
                        GUI.libraryInchargeInterfacePanel.showRequestResult("user has pending record, profile not verified");
                        break;
                    case "NOT_VERIFIED":
                        GUI.libraryInchargeInterfacePanel.showRequestResult("user profile not verified");
                        break;
                    case "ALREADY_VERIFIED":
                        GUI.libraryInchargeInterfacePanel.showRequestResult("user profile was already verified");
                        break;
                    default:
                        GUI.libraryInchargeInterfacePanel.showRequestResult(resultFromVerification);
                        break;
                }
            }
            }
            else{
                GUI.libraryInchargeInterfaceFrame.setEnabled(true);
                GUI.libraryInchargeInterfacePanel.showRequestResult("can not verify alumni student profile");
            }
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(VerifyStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_verifyButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if (alsoIssueBook) {
            GUI.libraryInchargeInterfacePanel.showRequestResult("user not verified, book didn't issued");
        } else if (alsoIssueReport) {
            GUI.libraryInchargeInterfacePanel.showRequestResult("user not verified, report didn't issued");
        } else {
            GUI.libraryInchargeInterfacePanel.showRequestResult("user not verified");
        }
        GUI.libraryInchargeInterfaceFrame.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(verifyStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(verifyStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(verifyStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(verifyStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VerifyStudentForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel academicYearLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel divisionLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel mobileNoLabel;
    private javax.swing.JLabel pendingRecordsLabel;
    private javax.swing.JLabel sacademicYearLabel;
    private javax.swing.JLabel sdivisionLabel;
    private javax.swing.JLabel semailLabel;
    private javax.swing.JLabel sfirstNameLabel;
    private javax.swing.JLabel slastNameLabel;
    private javax.swing.JLabel smobileNoLabel;
    private javax.swing.JLabel spendingRecordsLabel;
    private javax.swing.JLabel suniqueIDLabel;
    private javax.swing.JLabel susernameLabel;
    private javax.swing.JLabel sverificationLabel;
    private javax.swing.JLabel uniqueIDLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel verificationLabel;
    private javax.swing.JButton verifyButton;
    private javax.swing.JPanel verifyStudentPanel;
    private javax.swing.JLabel verifyStudentTitleLable;
    // End of variables declaration//GEN-END:variables
}
